source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# Just the Docs theme will be loaded via remote_theme in _config.yml
# No need to add it here when using GitHub Pages

# If you have any other plugins, install them here:
# group :jekyll_plugins do
#   gem "jekyll-feed"
# end

